name: Build Android GKI Kernel

on:
  workflow_dispatch:
    inputs:
      kernel_branch:
        description: "Kernel branch to build (e.g., android12-5.10)"
        required: true
        default: "android12-5.10"
      clang_version:
        description: "Clang version (e.g., clang-r530567)"
        required: true
        default: "clang-r530567"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      # Step 2: 设置系统依赖
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex libssl-dev libncurses5-dev
          sudo apt-get install -y ccache git-core python3 curl

      # Step 3: 安装 repo 工具
      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=~/bin:\$PATH" >> $GITHUB_ENV

      # Step 4: 下载 AOSP GKI 源码
      - name: Download AOSP GKI kernel source
        run: |
          mkdir -p kernel
          cd kernel
          repo init -u https://android.googlesource.com/kernel/common -b ${{ github.event.inputs.kernel_branch }}
          repo sync -j$(nproc)

      # Step 5: 下载指定版本的工具链
      - name: Download AOSP prebuilt clang
        run: |
          mkdir -p prebuilts/clang/host/linux-x86
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/${{ github.event.inputs.clang_version }}.tar.gz -O clang.tar.gz
          tar -xzf clang.tar.gz -C prebuilts/clang/host/linux-x86
          export PATH=$PATH:$PWD/prebuilts/clang/host/linux-x86/${{ github.event.inputs.clang_version }}/bin

      # Step 6: 配置内核
      - name: Configure kernel
        run: |
          cd kernel/common
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH=$PWD/prebuilts/clang/host/linux-x86/${{ github.event.inputs.clang_version }}/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          make O=out aarch64_gki_defconfig

      # Step 7: 编译内核
      - name: Build kernel
        run: |
          cd kernel/common
          export ARCH=arm64
          export PATH=$PWD/prebuilts/clang/host/linux-x86/${{ github.event.inputs.clang_version }}/bin:$PATH
          make -j$(nproc) O=out

      # Step 8: 上传编译输出
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: kernel/common/out/arch/arm64/boot/
