name: Build GKI Kernel with AnyKernel3 Packaging

on:
  workflow_dispatch:
    inputs:
      kernel_branch:
        description: "Kernel branch to build (e.g., common-android12-5.10)"
        required: true
        default: "common-android12-5.10"
      build_config:
        description: "Build config file (e.g., common/build.config.gki.aarch64)"
        required: true
        default: "common/build.config.gki.aarch64"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      # Step 2: 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex libssl-dev libncurses5-dev
          sudo apt-get install -y ccache git-core python3 curl gcc-aarch64-linux-gnu zip

      # Step 3: 安装 repo 工具
      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH" >> $GITHUB_ENV

      # Step 4: 同步内核源码
      - name: Sync AOSP kernel source
        run: |
          mkdir -p kernel
          cd kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b ${{ github.event.inputs.kernel_branch }}
          repo sync -j$(nproc) --no-clone-bundle --optimized-fetch

      # Step 5: 动态修改 build_config
      - name: Modify build_config for Docker, KVM, and LXC
        run: |
          config_file=kernel/${{ github.event.inputs.build_config }}
          echo "Modifying build config: $config_file"

          # 添加 Docker 支持相关配置
          ## Namespace 支持
          echo "CONFIG_NAMESPACES=y" >> $config_file
          echo "CONFIG_NET_NS=y" >> $config_file
          ## Cgroup 支持
          echo "CONFIG_CGROUPS=y" >> $config_file
          echo "CONFIG_CGROUP_CPU=y" >> $config_file
          echo "CONFIG_CGROUP_SCHED=y" >> $config_file
          echo "CONFIG_CGROUP_DEVICE=y" >> $config_file
          echo "CONFIG_CGROUP_FREEZER=y" >> $config_file
          echo "CONFIG_CGROUP_PIDS=y" >> $config_file
          ## OverlayFS 支持（用于文件系统层的支持）
          echo "CONFIG_OVERLAY_FS=y" >> $config_file
          ## Network 支持
          echo "CONFIG_VETH=y" >> $config_file
          echo "CONFIG_BRIDGE=y" >> $config_file
          echo "CONFIG_NF_NAT=y" >> $config_file
          echo "CONFIG_NF_CONNTRACK=y" >> $config_file
          echo "CONFIG_NETFILTER_XTABLES=y" >> $config_file

          # 添加 KVM 支持相关配置
          echo "CONFIG_VIRTUALIZATION=y" >> $config_file
          echo "CONFIG_KVM=y" >> $config_file
          echo "CONFIG_KVM_INTEL=y" >> $config_file    # 针对 Intel CPU
          echo "CONFIG_KVM_AMD=y" >> $config_file      # 针对 AMD CPU
          echo "CONFIG_KVM_ARM_HOST=y" >> $config_file # 针对 ARM64 CPU

          # 添加 LXC 支持相关配置
          ## Namespace 和 Cgroup 支持
          echo "CONFIG_UTS_NS=y" >> $config_file
          echo "CONFIG_IPC_NS=y" >> $config_file
          echo "CONFIG_PID_NS=y" >> $config_file
          ## AppArmor 支持
          echo "CONFIG_SECURITY_APPARMOR=y" >> $config_file
          echo "CONFIG_SECURITY_APPARMOR_HASH=y" >> $config_file
          echo "CONFIG_SECURITY_APPARMOR_HASH_DEFAULT=y" >> $config_file

          # 打印修改后的配置
          echo "Updated $config_file:"
          cat $config_file

      # Step 6: 构建内核
      - name: Build kernel with ThinLTO
        run: |
          cd kernel
          LTO=thin BUILD_CONFIG=${{ github.event.inputs.build_config }} build/build.sh

      # Step 7: 打包 AnyKernel3 ZIP 文件
      - name: Package AnyKernel3
        run: |
          # 克隆 AnyKernel3 项目
          git clone https://github.com/osm0sis/AnyKernel3.git anykernel3

          # 复制内核镜像
          cp kernel/out/arch/arm64/boot/Image.gz anykernel3/zImage || \
          cp kernel/out/arch/arm64/boot/Image anykernel3/zImage

          # 复制设备树文件（dtb）
          mkdir -p anykernel3/dtb
          cp kernel/out/arch/arm64/boot/dts/*.dtb anykernel3/dtb/

          # 如果需要内核模块，复制到模块目录
          mkdir -p anykernel3/modules
          cp kernel/out/lib/modules/**/*.ko anykernel3/modules/ || true

          # 压缩打包 AnyKernel3
          cd anykernel3
          zip -r9 AnyKernel3.zip ./*

      # Step 8: 上传 AnyKernel3 ZIP 文件
      - name: Upload AnyKernel3 ZIP
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3-package
          path: anykernel3/AnyKernel3.zip

      # Step 9: 上传内核镜像文件
      - name: Upload kernel image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: |
            kernel/out/arch/arm64/boot/Image.gz
            kernel/out/arch/arm64/boot/Image

      # Step 10: 上传模块文件
      - name: Upload kernel modules
        uses: actions/upload-artifact@v4
        with:
          name: kernel-modules
          path: kernel/out/lib/modules/**/*.ko

      # Step 11: 上传设备树文件
      - name: Upload dtb files
        uses: actions/upload-artifact@v4
        with:
          name: dtb-files
          path: kernel/out/arch/arm64/boot/dts/*.dtb
