name: Build GKI Kernel for Android 12 (5.10) with LXC & Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 安装构建依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential bc flex bison \
                              libssl-dev libelf-dev libncurses-dev \
                              dwarves cpio git wget xz-utils

      - name: 拉取 `android12-5.10` GKI 源码
        run: |
          git clone --depth=1 https://android.googlesource.com/kernel/common -b android12-5.10 gki
          cd gki
          git fetch origin
          git pull origin android12-5.10 --rebase

      - name: 应用最新 ASB 安全补丁
        run: |
          cd gki
          git pull --rebase origin android12-5.10-lts

      - name: 启用 LXC 和 Docker 相关内核选项
        run: |
          cd gki
          cat <<EOF >> arch/arm64/configs/gki_defconfig
          CONFIG_USER_NS=y
          CONFIG_MEMCG=y
          CONFIG_CGROUP_FREEZER=y
          CONFIG_CGROUP_DEVICE=y
          CONFIG_CGROUP_PIDS=y
          CONFIG_CGROUP_CPUACCT=y
          CONFIG_CPUSETS=y
          CONFIG_BLK_CGROUP=y
          CONFIG_NET_CLS_CGROUP=y
          CONFIG_CFS_BANDWIDTH=y
          CONFIG_FAIR_GROUP_SCHED=y
          CONFIG_CGROUP_NET_PRIO=y
          CONFIG_CGROUP_NET_CLASSID=y
          CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
          CONFIG_IPC_NS=y
          CONFIG_UTS_NS=y
          CONFIG_PID_NS=y
          CONFIG_NET_NS=y
          CONFIG_POSIX_MQUEUE=y
          CONFIG_KEYS=y
          CONFIG_SECCOMP=y
          CONFIG_SECCOMP_FILTER=y
          CONFIG_NETFILTER_XT_MATCH_OWNER=y
          CONFIG_NETFILTER_XT_MATCH_CGROUP=y
          CONFIG_NF_CONNTRACK=y
          CONFIG_NF_NAT=y
          CONFIG_VETH=y
          CONFIG_BRIDGE_NETFILTER=y
          EOF

      - name: 编译内核
        run: |
          cd gki
          make ARCH=arm64 gki_defconfig
          make ARCH=arm64 -j$(nproc)

      - name: 打包编译后的内核
        run: |
          cd gki
          mkdir -p out
          cp arch/arm64/boot/Image.gz-dtb out/
          tar -czvf gki-kernel-android12-5.10.tar.gz -C out .

      - name: 上传编译产物
        uses: actions/upload-artifact@v3
        with:
          name: gki-kernel-android12-5.10
          path: gki/gki-kernel-android12-5.10.tar.gz
