name: Build MTK Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: 安装依赖
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential flex bison libssl-dev bc libncurses-dev gcc-aarch64-linux-gnu

      # Step 3: 下载工具链
      - name: Download AOSP Toolchain
        run: |
          mkdir -p prebuilts/clang/host/linux-x86
          curl -L https://dl.google.com/android/repository/clang-r450784e.tar.gz -o clang-r450784e.tar.gz
          tar -xvf clang-r450784e.tar.gz -C prebuilts/clang/host/linux-x86
          rm clang-r450784e.tar.gz

      # Step 4: 拉取 AOSP GKI 内核源码
      - name: Clone AOSP GKI Kernel Source
        run: |
          git clone --depth=1 https://android.googlesource.com/kernel/common.git -b android-mainline gki

      # Step 5: 设置环境变量
      - name: Setup Environment Variables
        run: |
          echo "PATH=$GITHUB_WORKSPACE/prebuilts/clang/host/linux-x86/clang-r450784e/bin:$PATH" >> $GITHUB_ENV
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CROSS_COMPILE_COMPAT=arm-linux-gnueabi-" >> $GITHUB_ENV
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV

      # Step 6: 配置内核
      - name: Configure Kernel
        working-directory: gki
        run: |
          make defconfig
          ./scripts/config --enable CONFIG_KVM
          ./scripts/config --enable CONFIG_DOCKER
          make olddefconfig

      # Step 7: 编译内核
      - name: Build Kernel
        working-directory: gki
        run: |
          make -j$(nproc) CC=clang CROSS_COMPILE=aarch64-linux-gnu- LD=ld.lld Image.gz dtbs

      # Step 8: 上传结果
      - name: Upload Kernel Image
        uses: actions/upload-artifact@v3
        with:
          name: kernel-image
          path: gki/arch/arm64/boot/Image.gz
