name: DL Sync GKI Source to GitHub Branch

on:
  workflow_dispatch:
    inputs:
      gki_branch:
        description: "AOSP GKI branch to sync (e.g., common-android12-5.10)"
        required: true
        default: "common-android12-5.10"
      target_branch:
        description: "Target GitHub branch to push the GKI source (e.g., gki-n)"
        required: true
        default: "a12-5.10"

jobs:
  sync-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出目标分支代码
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }} # 检出目标分支
          fetch-depth: 0 # 确保完整克隆（便于推送）

      # Step 2: 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 curl aria2

      # Step 3: 安装 repo 工具
      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      # Step 4: 同步 GKI 源码
      - name: Sync AOSP GKI source
        run: |
          mkdir -p gki-source
          cd gki-source
          if [ ! -d ".repo" ]; then
            # 初始化 repo
            repo init -u https://android.googlesource.com/kernel/manifest -b ${{ github.event.inputs.gki_branch }}
          fi
          # 同步源码
          repo sync -j$(nproc) --no-clone-bundle --optimized-fetch

      # Step 5: 替换目标分支内容
      - name: Replace target branch content
        run: |
          # 清空当前分支的所有文件
          git rm -rf . || true
          # 将同步的 GKI 源码复制到当前仓库目录
          cp -r gki-source/* .
          # 添加新文件到 Git 索引
          git add .

      # Step 6: 提交并推送到 GitHub 分支
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Sync GKI source from AOSP branch ${{ github.event.inputs.gki_branch }}"
          git push origin HEAD:${{ github.event.inputs.target_branch }}
