name: DL Sync GKI Source to GitHub Branch

on:
  workflow_dispatch:
    inputs:
      gki_branch:
        description: "AOSP GKI branch to sync (e.g., common-android12-5.10)"
        required: true
        default: "common-android12-5.10"
      target_branch:
        description: "Target GitHub branch to push the GKI source (e.g., gki-n)"
        required: false
        default: ""

jobs:
  sync-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出目标仓库代码
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: 生成目标分支名称
      - name: Generate target branch name
        run: |
          if [ -z "${{ github.event.inputs.target_branch }}" ]; then
            target_branch=${{ github.event.inputs.gki_branch }}-sync
          else
            target_branch=${{ github.event.inputs.target_branch }}
          fi
          echo "target_branch=$target_branch" >> $GITHUB_ENV

      # Step 3: 检查目标分支是否存在
      - name: Check if target branch exists
        id: check_branch
        run: |
          if git ls-remote --heads origin $target_branch | grep -q $target_branch; then
            echo "Branch exists."
            echo "branch_exists=true" >> $GITHUB_ENV
          else
            echo "Branch does not exist. It will be created."
            echo "branch_exists=false" >> $GITHUB_ENV
          fi

      # Step 4: 切换到目标分支（如果不存在则创建）
      - name: Create or switch to target branch
        run: |
          if [ "${{ env.branch_exists }}" == "false" ]; then
            git checkout -b $target_branch
          else
            git checkout $target_branch
          fi

      # Step 5: 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 curl aria2

      # Step 5.1: 清理磁盘空间
      - name: Clean up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo rm -rf /home/runner/work/_temp
          df -h

      # Step 6: 安装 repo 工具
      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      # Step 7: 同步 GKI 源码
      - name: Sync AOSP GKI source
        run: |
          rm -rf gki-source
          mkdir -p gki-source
          cd gki-source
          repo init -u https://android.googlesource.com/kernel/manifest -b ${{ github.event.inputs.gki_branch }} --depth=1
          repo sync -j$(nproc) --no-clone-bundle --optimized-fetch | tee sync.log
          cd ..

      # Step 7.2: 上传同步日志
      - name: Upload repo sync log
        uses: actions/upload-artifact@v4
        with:
          name: repo-sync-log
          path: gki-source/sync.log

      # Step 8: 替换目标分支内容
      - name: Replace target branch content
        run: |
          git rm -rf . || true
          mv gki-source/* .
          git add -A

      # Step 9: 提交并推送到 GitHub 分支
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping push."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Sync GKI source from AOSP branch ${{ github.event.inputs.gki_branch }}"
          git push origin $target_branch --force
